name: mandalina
description: movieTime
version: 1.0.0+3

environment:
  sdk: ">=2.2.2 <3.0.0"

moduel:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_cache_manager: ^1.1.3
  rxdart: ^0.20.0
  http: ^0.12.0
  wakelock: ^0.1.3
  video_player: ^0.10.5
  cached_network_image: ^2.0.0-rc
  transparent_image: ^1.0.0
  fluro:
    git: https://github.com/devdennysegura/fluro.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/images/Netflix-logo.png
   - assets/images/netflix_icon.png
   - assets/images/1.5x/netflix_icon.png
   - assets/images/2.0x/netflix_icon.png
   - assets/images/3.0x/netflix_icon.png
   - assets/images/4.0x/netflix_icon.png
   - assets/images/loader.gif

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/product-sans/regular.ttf
          weight: 400
        - asset: assets/fonts/product-sans/bold.ttf
          weight: 700
        - asset: assets/fonts/product-sans/bold-italic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/product-sans/medium.ttf
          weight: 600
        - asset: assets/fonts/product-sans/medium-italic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/product-sans/italic.ttf
          style: italic
